--[[
Name: LibBabble-PetFamily-3.0
Revision: $Rev: 2 $
Maintainers: 
Website: 
Dependencies: None
License: MIT
]]

local MAJOR_VERSION = "LibBabble-PetFamily-3.0"
local MINOR_VERSION = 90000 + tonumber(("$Rev: 1 $"):match("%d+"))

if not LibStub then error(MAJOR_VERSION .. " requires LibStub.") end
local lib = LibStub("LibBabble-3.0"):New(MAJOR_VERSION, MINOR_VERSION)
if not lib then return end

local GAME_LOCALE = GetLocale()

lib:SetBaseTranslations {
	["Aqiri"] = "Aqiri",
	["Basilisk"] = "Basilisk",
	["Bat"] = "Bat",
	["Bear"] = "Bear",
	["Beetle"] = "Beetle",
	["Bird of Prey"] = "Bird of Prey",
	["Blood Beast"] = "Blood Beast",
	["Boar"] = "Boar",
	["Camel"] = "Camel",
	["Carapid"] = "Carapid",
	["Carrion Bird"] = "Carrion Bird",
	["Cat"] = "Cat",
	["Chimaera"] = "Chimaera",
	["Clefthoof"] = "Clefthoof",
	["Core Hound"] = "Core Hound",
	["Courser"] = "Courser",
	["Crab"] = "Crab",
	["Crocolisk"] = "Crocolisk",
	["Devilsaur"] = "Devilsaur",
	["Direhorn"] = "Direhorn",
	["Dragonhawk"] = "Dragonhawk",
	["Feathermane"] = "Feathermane",
	["Fox"] = "Fox",
	["Gorilla"] = "Gorilla",
	["Gruffhorn"] = "Gruffhorn",
	["Hound"] = "Hound",
	["Hydra"] = "Hydra",
	["Hyena"] = "Hyena",
	["Lesser Dragonkin"] = "Lesser Dragonkin",
	["Lizard"] = "Lizard",
	["Mammoth"] = "Mammoth",
	["Mechanical"] = "Mechanical",
	["Monkey"] = "Monkey",
	["Moth"] = "Moth",
	["Oxen"] = "Oxen",
	["Pterrordax"] = "Pterrordax",
	["Raptor"] = "Raptor",
	["Ravager"] = "Ravager",
	["Ray"] = "Ray",
	["Riverbeast"] = "Riverbeast",
	["Rodent"] = "Rodent",
	["Scalehide"] = "Scalehide",
	["Scorpid"] = "Scorpid",
	["Serpent"] = "Serpent",
	["Shale Beast"] = "Shale Beast",
	["Spider"] = "Spider",
	["Spirit Beast"] = "Spirit Beast",
	["Sporebat"] = "Sporebat",
	["Stag"] = "Stag",
	["Stone Hound"] = "Stone Hound",
	["Tallstrider"] = "Tallstrider",
	["Toad"] = "Toad",
	["Turtle"] = "Turtle",
	["Warp Stalker"] = "Warp Stalker",
	["Wasp"] = "Wasp",
	["Water Strider"] = "Water Strider",
	["Waterfowl"] = "Waterfowl",
	["Wind Serpent"] = "Wind Serpent",
	["Wolf"] = "Wolf",
	["Worm"] = "Worm"
}

if GAME_LOCALE == "enUS" then
	lib:SetCurrentTranslations(true)

elseif GAME_LOCALE == "esES" then
	lib:SetCurrentTranslations {
	["Aqiri"] = "Aqir",
	["Basilisk"] = "Basilisco",
	["Bat"] = "Murciélago",
	["Bear"] = "Oso",
	["Beetle"] = "Alfazaque",
	["Bird of Prey"] = "Ave rapaz",
	["Blood Beast"] = "Bestia de sangre",
	["Boar"] = "Jabalí",
	["Camel"] = "Camello",
	["Carapid"] = "Carápido",
	["Carrion Bird"] = "Carroñero",
	["Cat"] = "Felino",
	["Chimaera"] = "Quimera",
	["Clefthoof"] = "Uñagrieta",
	["Core Hound"] = "Can del Núcleo",
	["Courser"] = "Trotador",
	["Crab"] = "Cangrejo",
	["Crocolisk"] = "Crocolisco",
	["Devilsaur"] = "Demosaurio",
	["Direhorn"] = "Cuernoatroz",
	["Dragonhawk"] = "Dracohalcón",
	["Feathermane"] = "Cuellipluma",
	["Fox"] = "Zorro",
	["Gorilla"] = "Gorila",
	["Gruffhorn"] = "Broncocuerno",
	["Hound"] = "Can",
	["Hydra"] = "Hidra",
	["Hyena"] = "Hiena",
	["Lesser Dragonkin"] = "Dragonante inferior",
	["Lizard"] = "Lagarto",
	["Mammoth"] = "Mamut",
	["Mechanical"] = "Máquina",
	["Monkey"] = "Mono",
	["Moth"] = "Palomilla",
	["Oxen"] = "Buey",
	["Pterrordax"] = "Pterrordáctilo",
	["Raptor"] = "Raptor",
	["Ravager"] = "Devastador",
	["Ray"] = "Raya",
	["Riverbeast"] = "Bestia fluvial",
	["Rodent"] = "Roedor",
	["Scalehide"] = "Pielescama",
	["Scorpid"] = "Escórpido",
	["Serpent"] = "Serpiente",
	["Shale Beast"] = "Bestia de esquisto",
	["Spider"] = "Araña",
	["Spirit Beast"] = "Bestia espíritu",
	["Sporebat"] = "Esporiélago",
	["Stag"] = "Venado",
	["Stone Hound"] = "Can de piedra",
	["Tallstrider"] = "Zancaalta",
	["Toad"] = "Sapo",
	["Turtle"] = "Tortuga",
	["Warp Stalker"] = "Acechador deformado",
	["Wasp"] = "Avispa",
	["Water Strider"] = "Zancudo acuático",
	["Waterfowl"] = "Ave fluvial",
	["Wind Serpent"] = "Dragón alado",
	["Wolf"] = "Lobo",
	["Worm"] = "Gusano"
}
elseif GAME_LOCALE == "deDE" then
	lib:SetCurrentTranslations(true)
elseif GAME_LOCALE == "frFR" then
	lib:SetCurrentTranslations {
	["Aqiri"] = "Aqir",
	["Basilisk"] = "Basilic",
	["Bat"] = "Chauve-souris",
	["Bear"] = "Ours",
	["Beetle"] = "Hanneton",
	["Bird of Prey"] = "Oiseau de proie",
	["Blood Beast"] = "Bête de sang",
	["Boar"] = "Sanglier",
	["Camel"] = "Dromadaire",
	["Carapid"] = "Carapide",
	["Carrion Bird"] = "Charognard",
	["Cat"] = "Félin",
	["Chimaera"] = "Chimère",
	["Clefthoof"] = "Sabot-fourchu",
	["Core Hound"] = "Chien du magma",
	["Courser"] = "Coursier",
	["Crab"] = "Crabe",
	["Crocolisk"] = "Crocilisque",
	["Devilsaur"] = "Diablosaure",
	["Direhorn"] = "Navrecorne",
	["Dragonhawk"] = "Faucon-dragon",
	["Feathermane"] = "Crin-de-plume",
	["Fox"] = "Renard",
	["Gorilla"] = "Gorille",
	["Gruffhorn"] = "Raucorne",
	["Hound"] = "Molosse",
	["Hydra"] = "Hydre",
	["Hyena"] = "Hyène",
	["Lesser Dragonkin"] = "Draconien inférieur",
	["Lizard"] = "Lézard",
	["Mammoth"] = "Mammouth",
	["Mechanical"] = "Mécanique",
	["Monkey"] = "Singe",
	["Moth"] = "Phalène",
	["Oxen"] = "Bovin",
	["Pterrordax"] = "Pterreurdactyle",
	["Raptor"] = "Raptor",
	["Ravager"] = "Ravageur",
	["Ray"] = "Raie",
	["Riverbeast"] = "Potamodonte",
	["Rodent"] = "Rongeur",
	["Scalehide"] = "Peau écailleuse",
	["Scorpid"] = "Scorpide",
	["Serpent"] = "Serpent",
	["Shale Beast"] = "Bête de schiste",
	["Spider"] = "Araignée",
	["Spirit Beast"] = "Esprit de bête",
	["Sporebat"] = "Sporoptère",
	["Stag"] = "Cerf",
	["Stone Hound"] = "Molosse de pierre",
	["Tallstrider"] = "Haut-trotteur",
	["Toad"] = "Crapaud",
	["Turtle"] = "Tortue",
	["Warp Stalker"] = "Traqueur dim.",
	["Wasp"] = "Guêpe",
	["Water Strider"] = "Trotteur aquatique",
	["Waterfowl"] = "Canard",
	["Wind Serpent"] = "Serpent des vents",
	["Wolf"] = "Loup",
	["Worm"] = "Ver"
}
elseif GAME_LOCALE == "koKR" then
	lib:SetCurrentTranslations(true)
elseif GAME_LOCALE == "esMX" then
	lib:SetCurrentTranslations(true)
elseif GAME_LOCALE == "ptBR" then
	lib:SetCurrentTranslations(true)
elseif GAME_LOCALE == "itIT" then
	lib:SetCurrentTranslations {
	["Aqiri"] = "Aqiri",
	["Basilisk"] = "Basilisco",
	["Bat"] = "Pipistrello",
	["Bear"] = "Orso",
	["Beetle"] = "Scarabeo",
	["Bird of Prey"] = "Rapace",
	["Blood Beast"] = "Bestia di Sangue",
	["Boar"] = "Cinghiale",
	["Camel"] = "Dromedario",
	["Carapid"] = "Carapide",
	["Carrion Bird"] = "Mangiacarogne",
	["Cat"] = "Felino",
	["Chimaera"] = "Chimera",
	["Clefthoof"] = "Mammuceronte",
	["Core Hound"] = "Segugio del Nucleo",
	["Courser"] = "Corsiero",
	["Crab"] = "Granchio",
	["Crocolisk"] = "Crocolisco",
	["Devilsaur"] = "Gigantosauro",
	["Direhorn"] = "Cornofurente",
	["Dragonhawk"] = "Dragofalco",
	["Feathermane"] = "Piumanto",
	["Fox"] = "Volpe",
	["Gorilla"] = "Gorilla",
	["Gruffhorn"] = "Cornorude",
	["Hound"] = "Segugio",
	["Hydra"] = "Idra",
	["Hyena"] = "Iena",
	["Lesser Dragonkin"] = "Dragoide Minore",
	["Lizard"] = "Lucertola",
	["Mammoth"] = "Mammut",
	["Mechanical"] = "Unità Meccanica",
	["Monkey"] = "Scimmia",
	["Moth"] = "Falena",
	["Oxen"] = "Yak",
	["Pterrordax"] = "Pterrordattilo",
	["Raptor"] = "Raptor",
	["Ravager"] = "Devastatore",
	["Ray"] = "Pastinaca",
	["Riverbeast"] = "Bestia dei Fiumi",
	["Rodent"] = "Roditore",
	["Scalehide"] = "Scagliamanto",
	["Scorpid"] = "Scorpide",
	["Serpent"] = "Serpente",
	["Shale Beast"] = "Bestia Rocciosa",
	["Spider"] = "Ragno",
	["Spirit Beast"] = "Bestia Eterea",
	["Sporebat"] = "Sporofago",
	["Stag"] = "Cervo",
	["Stone Hound"] = "Segugio di Pietra",
	["Tallstrider"] = "Zampalunga",
	["Toad"] = "Rospo",
	["Turtle"] = "Tartaruga",
	["Warp Stalker"] = "Segugio Distorcente",
	["Wasp"] = "Vespa",
	["Water Strider"] = "Gerride",
	["Waterfowl"] = "Uccello Marino",
	["Wind Serpent"] = "Serpente Volante",
	["Wolf"] = "Lupo",
	["Worm"] = "Verme"
}
elseif GAME_LOCALE == "ruRU" then
	lib:SetCurrentTranslations(true)
elseif GAME_LOCALE == "zhCN" then
	lib:SetCurrentTranslations(true)
elseif GAME_LOCALE == "zhTW" then
	lib:SetCurrentTranslations(true)
else
	error(("%s: Locale %q not supported"):format(MAJOR_VERSION, GAME_LOCALE))
end
